### ISSUE TITLE
Unable to use the image due to permission denied error. 

### ISSUE THREAD

**Issue by ggoosen** [williamjacksn/docker-netlify-cli#123]
command used to run below 
tried with sudo and without

sudo docker container run -it     -e NETLIFY_AUTH_TOKEN=xxxxxxREDACTEDxxxxxxx
MIxm4     -v /home/projects/al/Ai/frontend:/project     williamjackson/netlify
-cli     deploy
This folder isn't linked to a site yet
? What would you like to do? Link this directory to an existing site
    Error: EACCES: permission denied, open '/project/.gitignore'
    Code: EACCES

**Comment by williamjacksn** [comment]
Inside the container, the tool is running as the user with id 1000 by default. If your project files are owned by a different user, you will need to run the container as the user that owns the files:


```
# ls -n /path/to/project/.gitignore
-rw-r--r-- 1 1001 1001 35 Feb 25 22:06 /path/to/project/.gitignore
             ^^^^ file is owned by user with id 1001

# docker container run -it -u 1001 -e NETLIFY_AUTH_TOKEN=REDACTED -v /home/projects/al/Ai/frontend:/project williamjackson/netlify-cli deploy
                           ^^^^^^^ run container as user with id 1001
```

**Comment by clair-hu-525** [comment]
![Screen Shot 2021-06-14 at 10 54 02 AM](https://user-images.githubusercontent.com/84792813/121912783-dc04e580-ccfe-11eb-9a49-e48ce6d60792.png)
The user is set to id 1000 by `sudo chown`, but still no permission.

**Comment by williamjacksn** [comment]
@clair-hu-525 Perhaps you can start a shell in the container and inspect the file permissions to verify?

    docker-compose run --rm --entrypoint sh netlify-cli

**Comment by clair-hu-525** [comment]
![Screen Shot 2021-06-14 at 1 00 21 PM](https://user-images.githubusercontent.com/84792813/121930560-83d6df00-cd10-11eb-88af-bcff2721c1a1.png)
it seems that the /project has no .gitignore. maybe the mounting is not working?

**Comment by williamjacksn** [comment]
Yeah. Do you have volumes defined in your `docker-compose.yaml` file? It looks like you are also using a devcontainer configuration in VS Code, and I'm not very familiar with that and whether it is interfering.
