### ISSUE TITLE
Using netlify dev --live with the container

### ISSUE THREAD

**Issue by t-richard** [williamjacksn/docker-netlify-cli#38]
Hi @williamjacksn !

First, thanks for the work you've done here at making and keeping this container up-to-date :slightly_smiling_face: 

I'm trying to get the `netlify dev --live` command working with the container.

`netlify dev` works just fine, but when adding the `--live` flag, it works but if I stop changing the code for a couple of minutes then it suddenly stops with this error

```
ERRO[0152] Failed to convert http response to outgoing response  error="unexpected EOF" request_id=xxxx
ERRO[0152] Error in http stream error="unexpected EOF"
```

When running the CLI on my host machine, it works fine even with `--live`.

Have you ever tried this out or got this error before ?

**Comment by williamjacksn** [comment]
I have never tried this before, so I am not sure how to approach debugging it.
