### ISSUE TITLE
Parse json

### ISSUE THREAD

**Issue by holyhope** [williamjacksn/docker-netlify-cli#407]
Hello,

Considering [`netlify api` command](https://cli.netlify.com/commands/api) which return json data, could we add [`jq` package](https://stedolan.github.io/jq/) to the docker image please?

Thanks to jq we could run smart [`listSiteDeploys`](https://open-api.netlify.com/#tag/deploy/operation/listSiteDeploys) command, for exemple:

```bash
netlify api listSiteDeploys --data '{"site_id": "'$NETLIFY_SITE_ID'"}' | jq -r '.[] | select(.state == "ready").id'
```

wdyt?

### Suggested solution:

```dockerfile
RUN apk update && apk add jq
```

**Comment by williamjacksn** [comment]
`jq` is now in the image, starting with `10.17.0`.
