### ISSUE TITLE
Bundle edge functions on Mac M1

### ISSUE THREAD

**Issue by njordhov** [williamjacksn/docker-netlify-cli#483]
Thank you for providing this docker image.

However, using netlify-cli (13.1.1) in a docker container on Mac M1 fails when attempting to build or deploy with edge functions. 

It might have to do with Deno not having a build for alpine or aarch64 linux. However, I have been unable to resolve or work around the issue - declaring linux/amd64 as platform does for example not make a difference.

With the hope that somebody else has relevant insight, here is a repo that can be used to replicate the problem:

https://github.com/njordhov/docker-netlify-cli-example

**Comment by njordhov** [comment]
Good news: Deploy is no longer failing with netlify-cli 13.1.3 although build still fails as before.

**Comment by williamjacksn** [comment]
I'm curious to know if recent updates to netlify-cli have resolved this for you.

**Comment by njordhov** [comment]
@williamjacksn Thanks for following up. Unfortunately, `docker compose run netlify-cli build` still reports "a problem setting up the Edge Functions environment" even after updating the docker image it uses to ghcr.io/williamjacksn/netlify-cli:14.1.0

I have since moved on to publish to netlify from a github repo as a work-around to get edge functions to deploy properly.

**Comment by williamjacksn** [comment]
I'm getting ready to archive this repository. I am going to close this old issue. I do not use this software myself anymore.
